# This workflow will build and push a node.js application to an Azure Web App when a commit is pushed to your default branch.
#
# This workflow assumes you have already created the target Azure App Service web app.
# For instructions see https://docs.microsoft.com/en-us/azure/app-service/quickstart-nodejs?tabs=linux&pivots=development-environment-cli
#
# To configure this workflow:
#
# 1. Download the Publish Profile for your Azure Web App. You can download this file from the Overview page of your Web App in the Azure Portal.
#    For more information: https://docs.microsoft.com/en-us/azure/app-service/deploy-github-actions?tabs=applevel#generate-deployment-credentials
#
# 2. Create a secret in your repository named AZURE_WEBAPP_PUBLISH_PROFILE, paste the publish profile contents as the value of the secret.
#    For instructions on obtaining the publish profile see: https://docs.microsoft.com/azure/app-service/deploy-github-actions#configure-the-github-secret
#
# 3. Change the value for the AZURE_WEBAPP_NAME. Optionally, change the AZURE_WEBAPP_PACKAGE_PATH and NODE_VERSION environment variables below.
#
# For more information on GitHub Actions for Azure: https://github.com/Azure/Actions
# For more information on the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# For more samples to get started with GitHub Action workflows to deploy to Azure: https://github.com/Azure/actions-workflow-samples

name: Update HTML

on:
  push:
    branches:
      - main # または、あなたのデフォルトブランチ名に変更

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: List images
      run: |
        # 画像を表示したいディレクトリへ移動
        cd ../../basic-tutorial/4章画像

        # 画像ファイルのリストを取得
        images=$(ls -1 *.jpg *.png)

        # HTMLファイルに画像を追加
        echo "<html><body>" > images.html
        for img in $images; do
          echo "<img src=\"$img\" alt=\"$img\">" >> images.html
        done
        echo "</body></html>" >> images.html
      shell: bash

    - name: Upload HTML
      uses: actions/upload-artifact@v2
      with:
        name: images-html
        path: images.html

