# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Image Display

on:
  push:
    branches:
      - main  # またはメインブランチの名前に合わせて変更

jobs:
  display_images:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Node.jsのバージョンを選択

    - name: Install dependencies
      run: npm install  # このステップで必要な依存関係をインストール

    - name: Display Images
      run: |
        # 画像表示のためのスクリプトを実行
        node display-images.js

